### ISSUE TITLE
A Error occured when using xpath to get nodelist from document

### ISSUE THREAD

**Issue by ysf0125** [HtmlUnit/htmlunit-neko#114]
A Error occurred when using xpath to get nodelist from document
When I used org.apache.xpath.XPathAPI to extract some nodes by xpath, the error occurred.
There is my error stack message
```
org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted.
        at org.htmlunit.cyberneko.xerces.dom.ParentNode.internalInsertBefore(ParentNode.java:332)
        at org.htmlunit.cyberneko.xerces.dom.ParentNode.insertBefore(ParentNode.java:267)
        at org.htmlunit.cyberneko.xerces.dom.NodeImpl.appendChild(NodeImpl.java:172)
        at org.htmlunit.cyberneko.html.dom.HTMLDocumentImpl.getDocumentElement(HTMLDocumentImpl.java:275)
        at org.apache.xpath.XPathAPI.eval(XPathAPI.java:233)
        at org.apache.xpath.XPathAPI.selectNodeList(XPathAPI.java:167)
        at org.apache.xpath.XPathAPI.selectNodeList(XPathAPI.java:147)

```
I found the two way may occur this error, 
1. project not import the serializer.jar 
2. add node to the document may occur this error.

I'm sure i has imported the  serializer.jar  to my project,so i guess may be the reason is happend when appending node.

**Comment by rbri** [comment]
Hi @ysf0125, thanks for your report.

Neko has a simple build in dom implementation that might not be perfect in all cases. To analyze this a bit deeper i need some more information from you. At least i need the htmlinput you are parsing and your parser code. Do you parse using the domparser or the domfragmentparser?

**Comment by rbri** [comment]
@ysf0125 sorry, can not reproduce your case here 
can you please attach the code of the method CommonUtil.xpathParse.getDomParser(html);

**Comment by ysf0125** [comment]
Sorry I forgot to attach the CommonUtil.xpathParse.getDomParser(html).
This is my function  CommonUtil.xpathParse.getDomParser(html).
```
public static DOMParser getDomParser(Object input) {
	XMLInputSource inputSource = null;
	if(input instanceof String){
		final StringReader sr = new StringReader((String) input);
		inputSource = new XMLInputSource(null, "foo", null, sr, null);
	}else if (input instanceof XMLInputSource) {
		inputSource = (XMLInputSource) input;
	}
	// use the provided simple DocumentImpl
	final DOMParser parser = new DOMParser(HTMLDocumentImpl.class);
	try {
		parser.parse(inputSource);
	} catch (IOException e) {
		throw new RuntimeException(e);
	}
	return parser;
}
```

**Comment by rbri** [comment]
@ysf0125 sorry but i'm still too stupid to reproduce your case here.

Any chance you can help me with this - maybe creating a single file having our html code as string inside and a simple main method that produces the error?

**Comment by ysf0125** [comment]
@rbri here is the whole code in one java file.
run the main function can occur this Exception.
[DomExceptionTest.zip](https://github.com/user-attachments/files/15532145/DomExceptionTest.zip)

**Comment by rbri** [comment]
@ysf0125 thanks, still was a bit tricky because i had to inclued xalan and fastjason but now i got it

**Comment by rbri** [comment]
@ysf0125 sorry for the long delay until i really got my hands on this.

I think a found the problem, the creation of HtmlElements was not aware of XHTML pages. This should be fixed now and a bunch of tests where added.

Please try the lastest snapshot build.... and provide feedback.

**Comment by rbri** [comment]
released
