### ISSUE TITLE
Duplicate forks of Nekohtml resulting in some confusion

### ISSUE THREAD

**Issue by LogeswaranRamasamy** [HtmlUnit/htmlunit-neko#117]
@rbri Can we use this [codelibs fork of nekohtml](https://github.com/codelibs/nekohtml) itself instead of htmlunit-neko as codelibs also seems to be a working fork without any major vulnerabilities. Else is codelibs.nekohtml project not being maintained & should we switch to [htmlunit-neko](https://github.com/HtmlUnit/htmlunit-neko).

Problem is [htmlunit-neko](https://github.com/HtmlUnit/htmlunit-neko) seems to use it's own version of [xerces2j jar](https://github.com/apache/xerces2-j) instead of xercesImpl. But xerces2j of htmlunit-neko doesn't seem to be actively maintained & couldn't find any Maven link to download xerces2j jar as well.

Kindly pls advice on this.

**Comment by rbri** [comment]
> Can we use this [codelibs fork of nekohtml](https://github.com/codelibs/nekohtml) itself instead of htmlunit-neko as codelibs also seems to be a working fork without any major vulnerabilities.

Yes you can!

> Problem is [htmlunit-neko](https://github.com/HtmlUnit/htmlunit-neko) seems to use it's own version of [xerces2j jar](https://github.com/apache/xerces2-j) instead of xercesImpl. But xerces2j of htmlunit-neko doesn't seem to be actively maintained & couldn't find any Maven link to download xerces2j jar as well.

Maybe the text on the home page is a bit misleading - htmlunit-neko uses a fork of xerces BUT all the forked code is now part of the neko-htmlunit.jar. neko-htmlunit.jar has no dependencies at all (at runtime). Therefore you do not have to search for a xerces / xml-api dependency.

Hope that helps....

**Comment by rbri** [comment]
@LogeswaranRamasamy and btw - [htmlunit-neko](https://github.com/HtmlUnit/htmlunit-neko) is in active development, we have done many, changes/fixes compared to the original nekohtml parser.

**Comment by rbri** [comment]
@LogeswaranRamasamy have updated the readme.md a bit - maybe you can have a look....

**Comment by LogeswaranRamasamy** [comment]
okk thanks readme.md seems to be clear now.

**Comment by rbri** [comment]
@LogeswaranRamasamy ok, will close this - hope you will give neko-htmlunit a try.
