### ISSUE TITLE
CloneNode is not working on org.w3c.dom.Node

### ISSUE THREAD

**Issue by LogeswaranRamasamy** [HtmlUnit/htmlunit-neko#119]
@rbri I am using htmlUnit-Neko parser to read an Html Document. I was able to successfully fetch the nodes but when I am trying to clone a org.w3c.dom.Node getting unimplemented Exception

java.lang.UnsupportedOperationException: unimplemented
	at org.htmlunit.cyberneko.util.SimpleArrayList.iterator(SimpleArrayList.java:234)
	at org.htmlunit.cyberneko.xerces.dom.AttributeMap.cloneContent(AttributeMap.java:388)
	at org.htmlunit.cyberneko.xerces.dom.AttributeMap.cloneMap(AttributeMap.java:367)
	at org.htmlunit.cyberneko.xerces.dom.ElementImpl.cloneNode(ElementImpl.java:146)
	
How to resolve this issue ?

**Comment by rschwietzke** [comment]
That is based on the performance tuning I applied. The simpler array list is not handling iterators at the moment. 
@rbri How about adding a test case and I will fix it over the weekend?

**Comment by LogeswaranRamasamy** [comment]
@rschwietzke thanks for the swift reply. Is there any other option/workaround to achieve CloneNode functionality at the moment ? Else any workaround available for this issue for the time being ?

**Comment by rschwietzke** [comment]
Well, you might be able to implement that yourself and just put that class in front of the classpath. You can optionally just fork HtmlUnit and replace `SimpleArrayList` in `AttributeMap` by an `ArrayList`, build it and add to your classpath.

**Comment by LogeswaranRamasamy** [comment]
Thanks @rschwietzke. Hope this will be fixed & pushed to the Maven repo soon ✌️

**Comment by rschwietzke** [comment]
If you could share your base code you use to create the failures, please? Might be a good base for a test case.

**Comment by rbri** [comment]
@rschwietzke will write some tests

**Comment by rbri** [comment]
@rschwietzke nothing to do for you - enjoy your weekend
@LogeswaranRamasamy thanks for giving this version a try - should be fixed now. please try with the latest snapshot build (4.2.0-SNAPSHOT)

**Comment by rbri** [comment]
@LogeswaranRamasamy can i close ris?

**Comment by rbri** [comment]
released
