### ISSUE TITLE
Remove reference to old xalan/xerces

### ISSUE THREAD

**Issue by tkupka** [HtmlUnit/htmlunit-neko#12]
Xalan/Xerces are implementing old JAXP. It's incompatible with newer JAXP implementation. So anyone using old impl might end up in:
`
 java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
`

**Comment by rbri** [comment]
Done - will be part of the 2.68.0 release.
You can use the latest snapshot if you like to test.
