### ISSUE TITLE
Selfclosing Break Line Tag <br /> tag in html content is converted into <br> open tag.

### ISSUE THREAD

**Issue by BloodDrag0n** [HtmlUnit/htmlunit-neko#122]
I am using antisamy to sanitize HTML contents. During the parsing of the HTML Data, the <br /> (self-closing) tag is converted into <br> (open tag). Is there any specific reason behind this behavior change? Is there any way to retain the <br /> tags?

Eg Input Html Data: `<p>this is para data</p><br/><p>this is para data 2</p>`

Eg Output Html Data: `<p>this is para data</p><br><p>this is para data 2</p>` 

HtmlUnit-Neko version using - 3.11.2
Antisamy version using - 1.7.5

**Comment by rbri** [comment]
hi @BloodDrag0n, looks like a bug, will have a look

**Comment by rbri** [comment]
@BloodDrag0n have added a test case but for me this looks ok from a first look. Any idea?

**Comment by rbri** [comment]
looks like the root cause is in antisamy - not in neko; see https://github.com/nahsra/antisamy/issues/484
