### ISSUE TITLE
Lowercase property gets ignored in DOM parser

### ISSUE THREAD

**Issue by radkovo** [HtmlUnit/htmlunit-neko#127]
When the `http://cyberneko.org/html/properties/names/elems` is set to `lower`, the DOM parser still returns uppercase element names.

The following code reproduces the problem:

```java
InputStream is = ...; // HTML input stream

DOMParser parser = new DOMParser(HTMLDocumentImpl.class);
parser.setProperty("http://cyberneko.org/html/properties/names/elems", "lower");
parser.setProperty("http://cyberneko.org/html/properties/names/attrs", "lower");

parser.parse(new org.xml.sax.InputSource(is));
doc = parser.getDocument();
// prints out 'lower'
System.out.println(parser.getXMLParserConfiguration().getProperty("http://cyberneko.org/html/properties/names/elems"));
// prints out 'HTML'
System.out.println(doc.getDocumentElement().getTagName());
```

The expected result (that worked with old nekohtml) is that the last line prints `html` instead of `HTML`.

**Comment by rbri** [comment]
@radkovo
i fear you are right - have to write some tests and check what triggered the change.

Will make a new snapshot hopefully soon

**Comment by rbri** [comment]
@radkovo sorry for that stupid bug - was a regression of an major update we dis some versions ago.
And at that time there was no real unit test for that part of the impl. The tests where added later and we used the wrong expectations.
Hopefully now everything is fixed.

Please try the latest snapshot build 4.7.0-SNAPSHOT

**Comment by radkovo** [comment]
Many thanks for a quick response. It's much better, almost all my tests have passed now :-) However, it seems that the last change breaks the functionality of (at least) `getElementsByTagName()` because in [HTMLDocumentImpl](https://github.com/HtmlUnit/htmlunit-neko/blob/master/src/main/java/org/htmlunit/cyberneko/html/dom/HTMLDocumentImpl.java#L471), the required tag name is converted to uppercase and later in the corresponding node list [DeepNodeListImpl](https://github.com/HtmlUnit/htmlunit-neko/blob/81888b9e95c3effb0f6af5cd03ab46c63050b57a/src/main/java/org/htmlunit/cyberneko/xerces/dom/DeepNodeListImpl.java#L191) the uppercase name is compared with `getTagName()`, which always fails as the DOM tag names have been converted to lowercase.

**Comment by rbri** [comment]
Will add some more test and fix that. But maybe it has to wait for the weekend....

**Comment by rbri** [comment]
@radkovo snapshot updated again

**Comment by rbri** [comment]
@radkovo your welcome

a next release might be available at the beginning of december

**Comment by rbri** [comment]
The release is there... enjoy.
