### ISSUE TITLE
HTMLTagBalancer does strange things with <table> inside <template> 

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit-neko#14]
# Problem in brief

When a `<table>` is inside a `<template>`, the resulting DOM tree is created with the table's children in a strange location.

# Reproducing

Here is a example HTML to reproduce the issue:

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
    
<template>
  <table>
    <tr>
      <ul></ul>
      <td></td>
    </tr>
  </table>
</template>
    
</body>
</html> 
```

* Note: The `<ul></ul>` isn't required for the test.  It's there just to demonstate a case where `HTMLTagBalancer` is correctly moving it outside of `<table>`.
    
Chrome creates this DOM tree:

```html
<!DOCTYPE html>
<html>
<head></head>
<body>

<template>
  <ul></ul>
  <table>
    <tbody>
      <tr>
        <td></td>
      </tr>
    </tbody>
  </table>
</template>

</body>
</html> 
```
    
HtmlUnit 2.66 creates this:

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
    
<template>
  <tr>
    <td></td>
  </tr>
  <ul></ul>
  <table></table>
</template>
    
</body>
</html>
```

* `<tr></tr>` is moved to a strange location
* `<tbody>` was not created

# More details

This issue cropped up as a regression when we updated HtmlUnit and is likely caused by this code:

https://github.com/HtmlUnit/htmlunit-neko/blob/e4f62269c986377a838c62aad94d4ea319249146/src/main/java/net/sourceforge/htmlunit/cyberneko/HTMLTagBalancer.java#L695-L697

The comment states `don't force/check parent for the direct template children` but there lacks a direct vs indirect check so perhaps the issue is caused by that. (I don't know what the test case for this new code is so this is just a guess.)

**Comment by rbri** [comment]
@duonglaiquang can't really reproduce your case with the current code base - do you use an older version?

**Comment by duonglaiquang** [comment]
@rbri I have no problem reproducing it using HtmlUnit version 2.66.0. 
I also ran the test again using the code from your new [commit](https://github.com/HtmlUnit/htmlunit-neko/commit/39f0dd15c70c82e883563294cbb54f92f4d50f43) and confirmed that it did fix the issue. 
Thank you for the quick response.

**Comment by rbri** [comment]
@duonglaiquang but moving the ul tag out of the table does not work at the moment.
Have you done the tests in HtmlUnit?

**Comment by rbri** [comment]
@duonglaiquang sorry for the confusion - have written your test case for htmlunit and now i see your point.
Simply enforcing the tbody fixes the issue from the htmlunit point of view.
The misplaced tr tag is from the HtmlUnitNekoDOMBuilder. Will have a deeper look at this and make a new snapshot build available on the weekend.

**Comment by rbri** [comment]
ok, done will make a new snapshot build soon (see twitter).
Many thanks for the detailed issue.
