### ISSUE TITLE
Porting guidance for v3.0.0?

### ISSUE THREAD

**Issue by davewichers** [HtmlUnit/htmlunit-neko#19]
Can you create a porting guide for this major new release? It's not just as simple as changing the imports.

For example, in my project: 
I changed all the imports as needed, but:
https://github.com/nahsra/antisamy/blob/main/src/main/java/org/owasp/validator/html/scan/MagicSAXFilter.java#L194 and L196, use new AugmentationsImpl(), but that class doesn't exist anymore. I tried setting them to just null, but that failed horribly.

There is now a branch that includes these changes called: upgradeCyberNekoHTMLUnit

Can you either explain to me what I need to do to finish porting over to your new 3.0.0. API, or even better fork my branch, fix it for me, and send me a pull request?  And then write a porting guide to help others, like me?

Hopefully this is an easy fix, but I don't see any good documentation that guides me on what I should be doing here.

Thanks, Dave

**Comment by rbri** [comment]
PR is there https://github.com/nahsra/antisamy/pull/322
