### ISSUE TITLE
<noscript> parsing problem

### ISSUE THREAD

**Issue by vivekchsm** [HtmlUnit/htmlunit-neko#2]
Hi,

I have noticed a parsing issue in htmlunit-neko with `<noscript>` tag. 
Consider the following inputs:
`<div><noscript><!-- </noscript> --></noscript>`
 `<div><noscript><img src="</noscript>"/></noscript>`

These are parsed as is, but in reality Noscript tag closes itself when it encounters the string `</noscript>` or `</noscript `. The weird part is, unlike other special tags like `<title>`, `<noframes>`, `<style>`, etc., `<noscript>` element values are parsed as HTML by all modern browsers.

This was identified while I discovered a security bypass in a third party whitelist HTML filter which is based on NekoHtml. As NekoHtml isn't maintained and while I checked this HtmlUnit's fork of Neko, many of NekoHtml's issues were fixed (like HTML comments parsing, etc) - so it would be great if we fix this, so that the users of NekoHtml would move to this fork.

And, I'm aware of `PARSE_NOSCRIPT_CONTENT` flag, but when it is set true, the element values are treated as text and not parsed. But, browsers treat them as HTML, which could possibly cause potential security issues. 

Possible fix:
We should parse Noscript's element values as HTML, but close the Noscript tag when the parser encounters the string `</noscript>` or `</noscript `.

Cheers,
Vivek Krishna

**Comment by rbri** [comment]
good point, any help is welcome

**Comment by rbri** [comment]
Hi @vivekchsm,

maybe a bit late but not forgotten.
Have written some more test for this https://github.com/HtmlUnit/htmlunit-neko/commit/eb717cd00edbd5d4107b7eaafe5eabe1489ab107 and it look like the neko behavior is now in sync with real browsers.

Hope you agree...

    ronald
