### ISSUE TITLE
Meet a Veracode issue.

### ISSUE THREAD

**Issue by yingqiangyu** [HtmlUnit/htmlunit-neko#22]
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/5174702/236406593-f9e3a8df-c4ee-4e3c-a0b5-8013ec006d3a.png">
https://cwe.mitre.org/data/definitions/597.html
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/5174702/236406771-dff3be32-da16-4bba-9147-65a77c369341.png">

Hi Rbri,
when we updated our esapi version in maven dependency, after veracode scanned, we meet this issue,
Could  we replace != with null verification and String.equals()

**Comment by yingqiangyu** [comment]
Thanks @rbri,
I met this issue when imported latest esapi dependency,
Thus it is transitive dependency.
After you publish 3.2.0  release, I'll let esapi know and update the dependency.

// https://mvnrepository.com/artifact/org.owasp.esapi/esapi
implementation group: 'org.owasp.esapi', name: 'esapi', version: '2.5.2.0'
->
// https://mvnrepository.com/artifact/org.owasp.antisamy/antisamy
implementation group: 'org.owasp.antisamy', name: 'antisamy', version: '1.7.3'
->
// https://mvnrepository.com/artifact/org.htmlunit/neko-htmlunit
implementation group: 'org.htmlunit', name: 'neko-htmlunit', version: '3.1.0'

**Comment by yingqiangyu** [comment]
Hi @rbri ,
I see latest change,
<img width="592" alt="image" src="https://user-images.githubusercontent.com/5174702/236676122-11fe4f09-8b6c-4de6-a949-b91dc33e9468.png">
I think there is potential NullPointException.
If prefix is null,  first half of the condition is false, then it will go through latter half of the condition. we will meet NullPointException.
Maybe we are able to use this condition to avoid NullPointException

if ( prefix != null ? prefix.equals(fNamespace[i - 2]) : prefix ==  fNamespace[i - 2])

**Comment by rbri** [comment]
Aaaaaaaaaaa - sorry....

**Comment by yingqiangyu** [comment]
Thanks, I see you use Objects.equals(), it's more readable than mine.
