### ISSUE TITLE
Should misplaced elements inside a table be parsed as appearing before the table?

### ISSUE THREAD

**Issue by salk31** [HtmlUnit/htmlunit-neko#7]
Hello,

I lost an afternoon to this one while writing some code to scrape a legacy system and migrate the data... Anyway, from a quick check Firefox and Chrome seem to parse the following:
```
<table>
<td>Callout Order</td></tr>
<h2>Motion Control:</h2>
<td>1st</td></tr>
```
as
```
<h2>Motion Control:</h2>
<table>
<tr><td>Callout Order</td></tr>
<tr><td>1st</td></tr>
</table>
```
ie bring the h2 forward.

I added a quick unit test and htmlunit-neko (latest ab9f8f5e3f5d48f6d9df046a55a26881afd2be06) seems to leave the h2 inside the table. 

Thanks for all the effort. I'm a, very, long time user of htmlunit/neko.

Cheers

Sam

**Comment by rbri** [comment]
Hi Sam,

thanks for your bug report. You are right, neko does not handle this case (and many others).  This is more or less the reason for all the complicated code in com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.

Regarding your case:

Have added some test to try to replicate your problem from the HtmlUnit viewpoint but was not able to produce your problem. Will be great if you can have a look at commit https://github.com/HtmlUnit/htmlunit/commit/e226ab07d70e6ee994ddec458b76ce9573284447 and try to add something similar that shows your problem. Without a test case i can't do anything real.

Again many thanks for your report

    RBRi

**Comment by salk31** [comment]
Thanks RBRi,

Will do. I reproduced it in the neko "canonical" tests. Will try with the htmlunit tests.

Cheers

Sam

**Comment by salk31** [comment]
Hi RBRi,

So I assume HTMLUnit does some more cleaning on top of neko?

Anyway, I believe the following test represents the problem I had:
```
    @Test
    @Alerts({"H2", "TABLE", "H2", "TABLE", "H2", "TABLE", "H2", "TABLE", "SCRIPT"})
    public void htmlTableMisplacedElementInside() throws Exception {
        final String html = ""
        		+ "<table><td></td></tr><h2>X</h2><td>1st</td></tr>\n"
        		+ "<table><td></td></tr><h2>Y</h2><td>1st</td></tr></table>\n"
        		+ "<h2>Z</h2><table><td></td><tr><td></td></table>\n"
        		+ "</table>\n"
        		+ "<h2>Z2</h2><table><td></td><tr><td>1st</td></table>\n"
        		+ "</table>\n"
        		+ "<script>\n"
        		+ "   var tmp = document.body.firstChild;\n"
        		+ "   while (tmp != null) {if (tmp.tagName) alert(tmp.tagName); tmp = tmp.nextSibling;}\n"
        		+ "</script>\n";
        loadPageWithAlerts2(html);
    }
```
I tested this in Chrome and Firefox and it does, what the author intended with heading then table... However if I cut it down much more the browsers start to have the same behaviour as htmlunit.

Pretty horrific HTML so I'd totally understand if don't want to tackle this one ;)

Cheers

Sam

**Comment by salk31** [comment]
NB Might make sense for me to edit the title of this issue as I wrote it based on the parsing just of neko. Seems like something else going on now.

**Comment by rbri** [comment]
Found some fixes for this in neko. The table handling if tables are inside tables was not correct. Hope that cures all your problems.
There i a new neko snapshot available. Hope i can publish a new HtmlUnit snapshot soon.

Please check twitter for updates.

**Comment by rbri** [comment]
New snapshots are out, can you please have a look.

**Comment by rbri** [comment]
No feedback - will close this.
Please open a new issue if you face further problems.

**Comment by salk31** [comment]
Thanks, sorry I've not had time to test it yet but your efforts are much appreciated.
