### ISSUE TITLE
Parameter endc is not used

### ISSUE THREAD

**Issue by rschwietzke** [HtmlUnit/htmlunit-neko#84]
We don't seem to use the parameter `endc` but have even two ways of calling this method (/ or ?). Is there anything missing, or just legacy?

https://github.com/HtmlUnit/htmlunit-neko/blob/06a2b01bd9bbd61c5c84043a311b78d9b779a64e/src/main/java/org/htmlunit/cyberneko/HTMLScanner.java#L3037

**Comment by rbri** [comment]
from a first look it seems to be legacy - will remove it but i guess i have to dig a bit more into that code to understand what is wrong here and to make sure the methods calling this and providing different values to the parameters are working correct.

**Comment by rbri** [comment]
done
