### ISSUE TITLE
Nested template tags not supported

### ISSUE THREAD

**Issue by jowerner** [HtmlUnit/htmlunit-neko#9]
Nested `<template>` tags are not supported yet. Recently I had a case similar to the following:

```html
<html>                   
    <head>                   
    </head>                   
    <body>           
        <div>                                                                          
            <template id="outer">                                                                                           
                <div>                                                                                                       
                    <template id="nested-1">                                                                                                                   
                    </template>                                                                                       
                </div>                                                                                       
                <template id="nested-2">                                                                                                        
                </template>                                                                           
            </template>        
        </div>              
    </body>
</html>
```

After loading this snippet with HtmlUnit's `WebClient.getPage()` and printing the page as XML, we get:

```html
<?xml version="1.0" encoding="ISO-8859-1"?>
<html>
  <head>
  </head>
  <body>
    <div>
      <template id="outer">
        <div>
        </div>
      </template>
      <template id="nested-1">
      </template>
    </div>
    <template id="nested-2">
    </template>
  </body>
</html>
```

Looks like the parser auto-closes the outer template (and also its div) when the first nested template is detected, effectively unnesting the inner templates.

**Comment by rbri** [comment]
Hi Joerg
will have a look at this later this week....

**Comment by rbri** [comment]
> Looks like the parser auto-closes the outer template (and also its div) when the first nested template is detected

correct, will fix this later this week

**Comment by jowerner** [comment]
Thanks a lot, Ronald. Hope the fix is not too complicated.

**Comment by rbri** [comment]
Its a simple configuration change and writing of some more tests.

And making sure i was not the one who introduces this from the logs ;-)

**Comment by rbri** [comment]
Made a new snapshot build available - thanks for the report.

**Comment by jowerner** [comment]
> Its a simple configuration change and writing of some more tests.

Ah, cool...

I tried the latest snapshot JAR and can confirm that the parser now works as expected with the case I had.
Thanks for your swift support!
